spring:
  datasource:
    url: jdbc:mysql://localhost/car_cred_fiap
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

email:
  gmail:
    smtp: smtp.gmail.com
    port: 587
    username: <gmail_email>
    password: <gmail_senha>

jwt:
  secret: fiap_mba_grupo_2
  expireInSeconds: 600

file:
  path:
    txt: classpath:/txt-sources/lista_alunos.txt